import {NextResponse} from 'next/server';
function publicUrl(req,path='/'){
  const host=(req.headers.get('x-forwarded-host')||req.headers.get('host')||'').split(',')[0].trim();
  const proto=(req.headers.get('x-forwarded-proto')||'https').split(',')[0].trim();
  if(host)return new URL(path,`${proto}://${host}`);
  const url=req.nextUrl.clone();url.pathname=path;url.search='';return url;
}
function noStaleAppCache(res){
  res.headers.set('Cache-Control','no-store, no-cache, max-age=0, must-revalidate');
  res.headers.set('Pragma','no-cache');
  res.headers.set('Expires','0');
  // Next App Router/RSC responses vary by these request headers. Explicit Vary helps
  // proxies/CDNs avoid serving a payload generated by a different navigation mode/build.
  res.headers.append('Vary','RSC');
  res.headers.append('Vary','Next-Router-State-Tree');
  res.headers.append('Vary','Next-Router-Prefetch');
  return res;
}
export function middleware(req){
  const p=req.nextUrl.pathname;
  if(p.startsWith('/_next')||p.startsWith('/img')||p==='/favicon.ico')return NextResponse.next();
  if(p==='/'||p==='/forgot-password'||p==='/reset-password'||p.startsWith('/api/auth'))return noStaleAppCache(NextResponse.next());
  if(!req.cookies.get('ot_session'))return noStaleAppCache(NextResponse.redirect(publicUrl(req,'/')));
  return noStaleAppCache(NextResponse.next());
}
export const config={matcher:['/((?!favicon.ico).*)']};
