'use client';
import {useMemo,useState} from 'react';
const ALLOWED=['application/pdf','image/jpeg','image/png','image/webp'];
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ')}
function inferDate(file){
  const p=file.webkitRelativePath||file.name||'';
  let m=p.match(/(20\d{2})[-_. ](\d{1,2})[-_. ](\d{1,2})/); if(m)return `${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`;
  m=p.match(/(\d{1,2})[-_. ](\d{1,2})[-_. ](20\d{2})/); if(m)return `${m[3]}-${String(m[1]).padStart(2,'0')}-${String(m[2]).padStart(2,'0')}`;
  const d=new Date(file.lastModified||Date.now()); return d.toISOString().slice(0,10);
}
export default function SharedriveImport({equipment}){
  const [files,setFiles]=useState([]),[status,setStatus]=useState({}),[busy,setBusy]=useState(false);
  const rows=useMemo(()=>files.map((file,i)=>{const path=file.webkitRelativePath||file.name;const n=norm(path);const match=equipment.find(e=>{const c=norm(e.code).trim();return c&&(` ${n} `).includes(` ${c} `)});return {i,file,path,match,date:inferDate(file),allowed:ALLOWED.includes(file.type)}}),[files,equipment]);
  const matched=rows.filter(r=>r.match&&r.allowed),unmatched=rows.length-matched.length;
  async function upload(){setBusy(true);for(const r of matched){if(status[r.i]==='done')continue;setStatus(s=>({...s,[r.i]:'uploading'}));const fd=new FormData();fd.set('equipmentId',r.match.id);fd.set('serviceDate',r.date);fd.set('relativePath',r.path);fd.set('displayName',r.file.name.replace(/\.[^.]+$/,''));fd.set('attachment',r.file);try{const res=await fetch('/api/admin/import-documents',{method:'POST',body:fd});if(!res.ok)throw new Error((await res.json()).error||'Upload failed');setStatus(s=>({...s,[r.i]:'done'}))}catch(e){setStatus(s=>({...s,[r.i]:`error: ${e.message}`}))}}setBusy(false)}
  return <div><div className="importDrop"><h2>Select Sharedrive / OneDrive Folder</h2><p className="muted">Choose a synchronized Microsoft Sharedrive/OneDrive folder. Files are matched automatically when their folder path or filename contains an equipment code.</p><input type="file" multiple webkitdirectory="" directory="" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={e=>{setFiles([...e.target.files]);setStatus({})}}/></div>{rows.length?<><div className="importStats"><span className="importStat good">{matched.length} ready to import</span><span className="importStat warn">{unmatched} need review</span><span className="importStat">{rows.length} total files</span></div><div className="importRows">{rows.map(r=><div className={`importRow ${!r.match||!r.allowed?'unmatched':''}`} key={r.i}><div><b>{r.file.name}</b><small className="muted">{r.path}</small></div><div>{r.match?<><b>{r.match.code}</b><small className="muted">{r.match.displayName||''}</small></>:<span className="importStatus bad">No equipment match</span>}</div><div>{r.date}</div><div>{!r.allowed?<span className="importStatus bad">Unsupported</span>:status[r.i]==='done'?<span className="importStatus ok">Imported</span>:status[r.i]?.startsWith('error')?<span className="importStatus bad">{status[r.i]}</span>:status[r.i]==='uploading'?'Uploading…':r.match?'Ready':'Review'}</div></div>)}</div><div style={{marginTop:14}}><button className="btn primary" disabled={busy||!matched.length} onClick={upload}>{busy?'Importing…':`Import ${matched.length} Matched File${matched.length===1?'':'s'}`}</button></div></>:null}</div>
}
