import { prisma } from './prisma';
import { sql } from './db';
import {computeStatus,validateReceiveInput,validateAdjustInput,validateCountInput,validateMarkOrdered} from './inventoryRules';
export class InventoryValidationError extends Error{constructor(errors){super(errors.join('; '));this.errors=errors}}
const requireUser=(userId)=>{if(!userId)throw new InventoryValidationError(['logged-in user required'])}
export async function receivePart({partId,locationId,qty,vendorId,cost,userId,notes}){requireUser(userId);const v=validateReceiveInput({qty,vendorId,cost});if(!v.valid)throw new InventoryValidationError(v.errors);const result=await prisma.$transaction(async tx=>{const i=await tx.partLocationInventory.findUniqueOrThrow({where:{partId_locationId:{partId,locationId}}});const onHand=i.onHand+qty,status=computeStatus(onHand,i.reorderWhenBelow);await tx.inventoryTransaction.create({data:{partId,locationId,type:'RECEIVE',qtyDelta:qty,vendorId,cost,userId,notes}});if(cost!=null)await tx.vendorPart.upsert({where:{vendorId_partId:{vendorId,partId}},update:{price:cost,lastPriceUpdate:new Date()},create:{vendorId,partId,price:cost,lastPriceUpdate:new Date()}});return tx.partLocationInventory.update({where:{partId_locationId:{partId,locationId}},data:{onHand,status}})});if(cost!=null){try{const vp=await prisma.vendorPart.findUnique({where:{vendorId_partId:{vendorId,partId}}});if(vp)await sql('INSERT INTO VendorPriceHistory(vendorPartId,price,recordedById) VALUES (?,?,?)',[vp.id,cost,userId])}catch{} }return result}
export async function adjustPart({partId,locationId,qtyDelta,reason,userId}){requireUser(userId);const v=validateAdjustInput({qtyDelta,reason});if(!v.valid)throw new InventoryValidationError(v.errors);return prisma.$transaction(async tx=>{const i=await tx.partLocationInventory.findUniqueOrThrow({where:{partId_locationId:{partId,locationId}}});const onHand=i.onHand+qtyDelta,status=computeStatus(onHand,i.reorderWhenBelow);await tx.inventoryTransaction.create({data:{partId,locationId,type:'ADJUST',qtyDelta,userId,notes:reason}});return tx.partLocationInventory.update({where:{partId_locationId:{partId,locationId}},data:{onHand,status}})})}
export async function recordCount({partId,locationId,actualCount,userId}){requireUser(userId);const v=validateCountInput({actualCount});if(!v.valid)throw new InventoryValidationError(v.errors);return prisma.$transaction(async tx=>{const i=await tx.partLocationInventory.findUniqueOrThrow({where:{partId_locationId:{partId,locationId}}});const delta=actualCount-i.onHand,status=computeStatus(actualCount,i.reorderWhenBelow);await tx.inventoryTransaction.create({data:{partId,locationId,type:'COUNT',qtyDelta:delta,userId,notes:'Physical count'}});return tx.partLocationInventory.update({where:{partId_locationId:{partId,locationId}},data:{onHand:actualCount,status}})})}
export async function markOrdered({partId,locationId,userId}){requireUser(userId);const i=await prisma.partLocationInventory.findUniqueOrThrow({where:{partId_locationId:{partId,locationId}}});const v=validateMarkOrdered(i.status);if(!v.valid)throw new InventoryValidationError(v.errors);return prisma.partLocationInventory.update({where:{partId_locationId:{partId,locationId}},data:{status:'on_order'}})}
