import AppShell from '../../../components/AppShell';
import ServiceAttachmentForm from '../../../components/ServiceAttachmentForm';
import ServiceRecordForm from '../../../components/ServiceRecordForm';
import EditServiceRecordForm from '../../../components/EditServiceRecordForm';
import DeleteButton from '../../../components/DeleteButton';
import AttachmentManager from '../../../components/AttachmentManager';
import { prisma } from '../../../lib/prisma';
import { sql } from '../../../lib/db';
import { notFound,redirect } from 'next/navigation';
import {getCurrentUser,userCanAccessLocation} from '../../../lib/session';
import {getServiceStatus} from '../../../lib/serviceStatus';
import QrPanel from '../../../components/QrPanel';
export const dynamic='force-dynamic';
export default async function EquipmentDetail({params}){
  const id=Number(params.id); if(!Number.isInteger(id)) notFound();
  const user=await getCurrentUser();
  const e=await prisma.equipment.findUnique({where:{id},include:{location:true,equipmentParts:{include:{part:{include:{locationStock:true}}}},machineHoursLogs:{orderBy:{recordedAt:'desc'},take:5},serviceIntervals:{orderBy:{id:'asc'}},serviceRecords:{include:{interval:true,performedBy:true,partsUsed:{include:{part:true,transaction:true}}},orderBy:{serviceDate:'desc'},take:50}}});
  if(!e||!userCanAccessLocation(user,e.locationId)) notFound();if(Number(user.locationId)!==Number(e.locationId))redirect(`/api/location/select?locationId=${e.locationId}&returnTo=${encodeURIComponent(`/equipment/${e.id}`)}`);
  const mileageRows=await sql('SELECT usesMileage,currentMileage FROM Equipment WHERE id=? LIMIT 1',[e.id]);const mileage=mileageRows[0]||{};const isAdmin=user?.role?.name==='Admin',canService=['Admin','Mechanic'].includes(user?.role?.name);
  const ids=e.serviceRecords.map(r=>r.id);
  const costRows=ids.length?await sql(`SELECT id,manualPartsCost,laborCost,externalCost FROM ServiceRecord WHERE id IN (${ids.map(()=>'?').join(',')})`,ids):[];
  const attachmentRows=ids.length?await sql(`SELECT id,serviceRecordId,displayName,notes,mimeType,fileName,uploadedAt FROM ServiceAttachment WHERE serviceRecordId IN (${ids.map(()=>'?').join(',')}) ORDER BY uploadedAt DESC`,ids):[];
  const costMap=new Map(costRows.map(r=>[Number(r.id),r])),attachmentMap=new Map();for(const a of attachmentRows){const k=Number(a.serviceRecordId);if(!attachmentMap.has(k))attachmentMap.set(k,[]);attachmentMap.get(k).push(a)}
  const history=e.serviceRecords.map(r=>{const c=costMap.get(r.id)||{};const inventoryPartsCost=r.partsUsed.reduce((sum,p)=>sum+Math.abs(p.transaction?.qtyDelta||0)*Number(p.transaction?.cost||0),0);const manualParts=Number(c.manualPartsCost||0),partsCost=inventoryPartsCost+manualParts,labor=Number(c.laborCost||0),external=Number(c.externalCost||0);return {...r,inventoryPartsCost,manualParts,partsCost,labor,external,total:partsCost+labor+external,attachments:attachmentMap.get(r.id)||[]}});
  const lifetime=history.reduce((s,r)=>s+r.total,0),partsLifetime=history.reduce((s,r)=>s+r.partsCost,0),laborLifetime=history.reduce((s,r)=>s+r.labor,0),externalLifetime=history.reduce((s,r)=>s+r.external,0),costPerHour=e.currentHours>0?lifetime/e.currentHours:0;
  return <AppShell title={`${e.code} — Equipment Detail`} active="Equipment">
    <div className="detailToolbar"><a className="btn" href="/equipment">← Equipment</a>{isAdmin?<a className="btn primary" href={`/equipment/${e.id}/edit`}>Edit Equipment</a>:null}</div>
    <div className="hero equipmentHero"><img src={`/api/equipment/${e.id}/photo`} alt={e.code}/><div><h2>{e.code}</h2><div className="heroName">{e.displayName||'Description not entered'}</div><div className="metaLine"><span className="hoursMeta"><b>{e.currentHours.toLocaleString()}</b> hrs{canService?<details className="quickHours"><summary>Update</summary><form action={`/api/equipment/${e.id}/hours`} method="post"><label>Current machine hours</label><div className="quickHoursRow"><input name="hours" type="number" min="0" step="0.1" defaultValue={e.currentHours} required/><button className="btn primary" type="submit">Save</button></div></form></details>:null}</span>{mileage.usesMileage&&mileage.currentMileage!=null?<span><b>{Number(mileage.currentMileage).toLocaleString()}</b> mi</span>:null}<span>{e.location.name}</span><span className={`equipStatus ${e.status.toLowerCase()}`}>{e.status.replaceAll('_',' ')}</span></div></div>{isAdmin?<QrPanel equipmentId={e.id} code={e.code} name={e.displayName}/>:null}</div>
    <div className="grid4" style={{marginTop:18}}><div className="metric"><small>Tracked Maintenance Cost</small><strong>${lifetime.toFixed(2)}</strong></div><div className="metric"><small>Parts Cost</small><strong>${partsLifetime.toFixed(2)}</strong></div><div className="metric"><small>Labor + Outside</small><strong>${(laborLifetime+externalLifetime).toFixed(2)}</strong></div><div className="metric"><small>Cost / Operating Hour</small><strong>${costPerHour.toFixed(2)}</strong></div></div>
    <div className="cols"><section className="card"><div className="toolbar"><h2>Parts for this Equipment</h2>{isAdmin?<a href={`/equipment/${e.id}/edit`} className="textLink">Manage Parts</a>:null}</div><div className="tablewrap"><table><thead><tr><th>Role</th><th>Part #</th><th>Description</th><th>On Hand</th></tr></thead><tbody>{e.equipmentParts.length?e.equipmentParts.map(ep=>{const inv=ep.part.locationStock.find(i=>i.locationId===e.locationId);return <tr key={ep.id}><td>{ep.partRole||'—'}</td><td><a className="tableLink" href={`/parts/${ep.partId}`}><b>{ep.part.internalPartNumber}</b></a></td><td>{ep.part.name}</td><td><b>{inv?.onHand??'—'}</b></td></tr>}):<tr><td colSpan="4" className="emptyCell">No parts linked yet.</td></tr>}</tbody></table></div></section>
    <section className="card"><div className="toolbar"><h2>Service Intervals</h2>{isAdmin?<a href={`/equipment/${e.id}/edit`} className="textLink">Manage Service</a>:null}</div>{e.serviceIntervals.length?e.serviceIntervals.map(s=>{const st=getServiceStatus(s,e.currentHours);return <div className="serviceRow" key={s.id}><div><b>{s.description}</b><div className="muted serviceMeta">{s.hoursValue?`Every ${s.hoursValue} hrs`:''}{s.hoursValue&&s.daysValue?' • ':''}{s.daysValue?`Every ${s.daysValue} days`:''}</div></div><div className={`serviceState ${st.key}`}>{st.label}<small>{st.remainingHours!=null?`${Math.round(st.remainingHours)} hrs`:st.remainingDays!=null?`${st.remainingDays} days`:''}</small></div></div>}):<div className="emptyCell">No service intervals configured yet.</div>}</section></div>
    <section className="card serviceDocumentsCard" style={{marginTop:18}}>
      <div className="toolbar"><div><h2>Service Documents</h2><div className="muted">Record service and attach invoices, work orders, inspection sheets, photos or other records directly from this equipment page.</div></div></div>
      {canService?<details className="equipmentQuickService"><summary className="btn primary">+ Record Service / Add Document</summary><div className="quickServiceBody"><ServiceRecordForm equipmentId={e.id} currentHours={e.currentHours} parts={e.equipmentParts.map(ep=>({id:ep.part.id,number:ep.part.internalPartNumber,name:ep.part.name,role:ep.partRole,onHand:ep.part.locationStock.find(i=>i.locationId===e.locationId)?.onHand??0}))} intervals={e.serviceIntervals}/></div></details>:null}
      {history.length?<div className="serviceDocumentGrid">{history.map(r=><div className="serviceDocumentRecord" key={`docs-${r.id}`}>
        <div className="serviceDocumentHeader"><div><b>{r.interval?.description||'Service'}</b><small>Service date: {new Date(r.serviceDate).toLocaleDateString()} • {r.hoursAtService.toLocaleString()} hrs • {r.performedBy.name}</small></div>{canService?<ServiceAttachmentForm serviceRecordId={r.id}/>:null}</div>
        <div className="serviceDocumentFiles">{r.attachments.length?r.attachments.map(d=><div className="serviceDocumentFile" key={d.id}><div><a className="tableLink" href={`/api/service-attachments/${d.id}`} target="_blank" rel="noreferrer"><b>{d.displayName}</b></a><small>{String(d.mimeType).includes('pdf')?'PDF':'Image'} • uploaded {new Date(d.uploadedAt).toLocaleDateString()}</small>{d.notes?<small>{d.notes}</small>:null}</div>{canService?<div className="attachmentActions"><AttachmentManager attachment={d} serviceDate={r.serviceDate}/><DeleteButton url={`/api/service-attachments/${d.id}`} label="Remove" confirmText={`Remove ${d.displayName}?`}/></div>:null}</div>):<div className="muted">No documents attached to this service record yet.</div>}</div>
      </div>)}</div>:<div className="emptyCell">No service records yet. Use “Record Service / Add Document” above to create one here.</div>}
    </section>
    <section className="card" style={{marginTop:18}}><div className="toolbar"><div><h2>Service History</h2><div className="muted">Tracked parts, labor, outside repair costs and service documents for this machine.</div></div>{isAdmin?<a className="textLink" href="/reports">View Reports</a>:null}</div><div className="tablewrap"><table><thead><tr><th>Date</th><th>Service</th><th>Hours</th><th>Parts Used</th><th>Parts $</th><th>Labor $</th><th>Outside $</th><th>Total</th><th>Performed By</th><th>Documents</th><th>Notes</th><th></th></tr></thead><tbody>{history.length?history.map(r=><tr key={r.id}><td>{new Date(r.serviceDate).toLocaleDateString()}</td><td>{r.interval?.description||'Service'}</td><td>{r.hoursAtService}</td><td>{r.partsUsed.map(p=>`${p.part.internalPartNumber} x${Math.abs(p.transaction?.qtyDelta||1)}`).join(', ')||'—'}</td><td>${r.partsCost.toFixed(2)}</td><td>${r.labor.toFixed(2)}</td><td>${r.external.toFixed(2)}</td><td><b>${r.total.toFixed(2)}</b></td><td>{r.performedBy.name}</td><td><div className="attachmentList">{r.attachments.map(d=><div className="attachmentItem" key={d.id}><a className="tableLink" href={`/api/service-attachments/${d.id}`} target="_blank" rel="noreferrer"><b>{d.displayName}</b></a><small>{String(d.mimeType).includes('pdf')?'PDF':'Image'} • uploaded {new Date(d.uploadedAt).toLocaleDateString()}</small>{d.notes?<small>{d.notes}</small>:null}{canService?<div className="attachmentActions"><AttachmentManager attachment={d} serviceDate={r.serviceDate}/><DeleteButton url={`/api/service-attachments/${d.id}`} label="Remove" confirmText={`Remove ${d.displayName}?`}/></div>:null}</div>)}{canService?<ServiceAttachmentForm serviceRecordId={r.id}/>:null}</div></td><td>{r.notes||'—'}</td><td>{canService?<EditServiceRecordForm record={{id:r.id,intervalId:r.intervalId,serviceDate:r.serviceDate.toISOString(),hoursAtService:r.hoursAtService,manualParts:r.manualParts,labor:r.labor,external:r.external,notes:r.notes}} intervals={e.serviceIntervals}/>:null}</td></tr>):<tr><td colSpan="12" className="emptyCell">No service history recorded yet.</td></tr>}</tbody></table></div></section>
  </AppShell>;
}
